USE hireme;

CREATE TABLE IF NOT EXISTS users (
    name VARCHAR(45) NOT NULL,
    email VARCHAR(120) NOT NULL,
    type VARCHAR(45) NOT NULL,
    password VARCHAR(45) NULL,
    UNIQUE INDEX email_UNIQUE (email),
    CHECK (type IN ('recruiter','client')),
    PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS recruiter (
    RID INT NOT NULL AUTO_INCREMENT,
    RName VARCHAR(45) NOT NULL,
    REmail VARCHAR(45) NOT NULL,
    CompanyName VARCHAR(45) NOT NULL,
    CompanyLocation VARCHAR(45) NOT NULL,
    RGender VARCHAR(2) NOT NULL,
    PRIMARY KEY (RID),
    UNIQUE (REmail)
);

CREATE TABLE IF NOT EXISTS client (
    CID INT NOT NULL AUTO_INCREMENT,
    CName VARCHAR(45) NOT NULL,
    CEmail VARCHAR(45) NOT NULL,
    CAge INT NOT NULL,
    CLocation VARCHAR(45) NOT NULL,
    CGender VARCHAR(2) NOT NULL,
    CExp INT NOT NULL,
    CSkills VARCHAR(45) NOT NULL,
    CQualification VARCHAR(45) NOT NULL,
    UNIQUE (CEmail),
    PRIMARY KEY (CID)
);

CREATE TABLE IF NOT EXISTS job (
    RID INT NOT NULL,
    JID INT NOT NULL AUTO_INCREMENT,
    JobRole VARCHAR(45) NOT NULL,
    JobType VARCHAR(45) NOT NULL,
    Qualification VARCHAR(45) NOT NULL,
    MinExp INT NOT NULL,
    Salary INT NOT NULL,
    FOREIGN KEY (RID) REFERENCES recruiter(RID),
    PRIMARY KEY (JID)
);

CREATE TABLE IF NOT EXISTS application (
    AID INT NOT NULL AUTO_INCREMENT,
    RID INT NOT NULL,
    JID INT NOT NULL,
    CID INT NOT NULL,
    PRIMARY KEY(AID),
    FOREIGN KEY(RID) REFERENCES recruiter(RID),
    FOREIGN KEY(JID) REFERENCES job(JID),
    FOREIGN KEY(CID) REFERENCES client(CID)
);